const HOME_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_HOME_BANNER_LIST_BEGIN: "GET_HOME_BANNER_LIST_BEGIN",
  GET_HOME_BANNER_LIST_SUCCESS: "GET_HOME_BANNER_LIST_SUCCESS",
  GET_HOME_BANNER_LIST_FAILURE: "GET_HOME_BANNER_LIST_FAILURE",

  GET_CLIENT_LIST_BEGIN: "GET_CLIENT_LIST_BEGIN",
  GET_CLIENT_LIST_SUCCESS: "GET_CLIENT_LIST_SUCCESS",
  GET_CLIENT_LIST_FAILURE: "GET_CLIENT_LIST_FAILURE",
};

export default HOME_TYPES;
